### ISSUE TITLE
Fix Travis build error

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/ws18-project-mas_maas#26]

**Comment by ErickKramer** [comment]
We found out that the agent that remains alive is the TimeKeeper agent. What should we do about it?

**Comment by argenos** [comment]
Fix it!

**Comment by argenos** [comment]
The long version of the answer above: At the beginning of the semester, I strongly recommended that you do not merge to master if the build is failing; if you are not listening to your checks, then I would start there. 

Secondly, I don't think you'd learn as much if you are only supposed to blindly follow instructions given by me, so instead,  to help you a bit with your independent work, please come up with three proposals of things *you* can do to fix this. Use some common sense about what is happening in the upstream repository, other team's who are also integrating this feature, and your own development skills.  

Shall we say tomorrow 12:00 for the proposals on how to solve this?

**Comment by anenriquez** [comment]
Sounds good. Just to clarify, do you mean we should meet tomorrow to discuss our proposals?

**Comment by argenos** [comment]
Not necessary, just post them here. I expect one possible solution per team member!

**Comment by ErickKramer** [comment]
Proposal solution to properly terminate the TimeKeeper Agent: 
* Inside the SendTimeStep behavior:
- We are currently calling the function getAllAgents() and iterating over all the agents found. 

**-> Proposal:** we could put a conditional statement and verify if agents.size() is equal to zero (meaning that no agent is currently alive) the TimeKeeper agent should terminate. 

Also, currently the timeKeeper agent inside the function TimeStepConfirmationBehaviour is waiting for an ACLMessage.INFORM, but any kind of ACL.Message.INFORM could trigger the behavior, even if was not meant for that agent. To avoid this, we should filter the messages by ConversationId.

**Comment by anenriquez** [comment]
Proposal solution for terminating the TimeKeeper Agent:

I agree with Erick in that the getAllAgents() function should be used to check if there 'alive' agents.

We could add a TickerBehavior that is constantly checking if there are agents and that triggers a shutdown behavior (like the one in the DummyAgent.java) when there are no agents found. Something like:

```
addBehaviour(new TickerBehaviour(this, 5000) {
            protected void onTick() {
                List<DFAgentDescription> agents = getAllAgents();
                if(agents.size() == 0){
                    System.out.println("There are no agents... terminating");
                    addBehaviour(new shutdown());
                }
            }

        } );
```

**Comment by emassey2** [comment]
I agree with all of the above but we should have a member variable to make sure that we don't shut down before we start. Bool minAgentsSeen = False; This can be set to true when one agent is seen. The if statement above would then be (agents.size() == 0 && minAgentsSeen)

Additionally, if we wanted, we could have another member variable and constant MIN_AGENTS_TO_SEE which is equal to a number greater than or equal to 1 and agentsSeen which is a counter that increases every time a new agent is encountered/registered. That way when agentsSeen >= MIN_AGENTS_TO_SEE we set minAgentsSeen to True.

**Comment by argenos** [comment]
Good! You also have an answer here: https://github.com/HBRS-MAAS/project/issues/52
Try to fix this ASAP

**Comment by argenos** [comment]
Your build is still erroring!
